### ISSUE TITLE
Validating UCUM with a long string and a dot causes infinite loop

### ISSUE THREAD

**Issue by adha-admin** [FirelyTeam/Fhir.Metrics#10]
Try:
                SystemOfUnits system = UCUM.Load();

                // Validate Unit
                Metric m = system.Metric("Suggestserumironstudiesonfastingspecimen.");

**Comment by alexzautke** [comment]
Hi there!
Thank you for reporting the issue. Unfortunately, I'm having a bit of trouble reproducing the infinity loop. For me loading UCUM and creating a metric as described above results in an appropriate error message. Could you maybe try to replicate your issue within a unit test and open a pull request reproducibly showing the unexpected behaviour?

Thank you!
