### ISSUE TITLE
validating UCUM's

### ISSUE THREAD

**Issue by philipwilford** [FirelyTeam/Fhir.Metrics#2]
This throws an error which is wrong? I was using this website as a guide.
https://lhncbc.github.io/ucum-lhc/demo.html
Can you confirm if this is an error in the code?

string unit = "10"

SystemOfUnits system = UCUM.Load();
// Validate Unit
Metric m = system.Metric(unit);

**Comment by mharthoorn** [comment]
It is probably your intension to use:
```cs
   string value = "10";
   var q = system.Quantity(value);
```
it will produce a quantity without a unit/dimension. 

See some of the unit tests for more details:
https://github.com/furore-fhir/Fhir.Metrics/blob/develop/test/Fhir.Metrics.Tests/Tests/TestQuantity.cs#L52
