### ISSUE TITLE
Regex Infinite Loop

### ISSUE THREAD

**Issue by philipwilford** [FirelyTeam/Fhir.Metrics#3]
We have random data to validate and this one just sends the code into an infinite loop.

            SystemOfUnits system = UCUM.Load();
            string unit = "ForinterpretationofeGFRseehttp://www.kidney.org.au";
            Metric m1 = system.Metric(unit);

I have isolated the issue and its to do with your TokenPattern
When this line is called, it just disappears.
bool valid = Regex.IsMatch(unit, TokenPattern);

So change
public static string TokenPattern = @"^(((?<m>[\.\/])?(?<m>[^\.\/]+))*)?$";
to be
public static string TokenPattern = @"(((?<m>[\.\/])?(?<m>[^\.\/]+))*)?";

This will fix the infinite loop

**Comment by mharthoorn** [comment]
Sorry for the long delay. The change is made. A new nuget will pushed soon. 
Plan to push it as netstandard2.0 (if no objections).

**Comment by mharthoorn** [comment]
A new package (v1.0.3) was pushed to nuget with this fix.
