### ISSUE TITLE
LeftSearchable fails if error margin is of same scale as value

### ISSUE THREAD

**Issue by cknaap** [FirelyTeam/Fhir.Metrics#5]
e.g. Quantity with value = 3M (note: decimal, not int) and unit = /a ('per year')

When you canonicalize this and then get the LeftSearchableString, it generates an ArrayOutOfBoundsException. See unittest in branch fix/arrayOutOfBoundsOnSlash

**Comment by alexzautke** [comment]
Fixed by PR #6
